---
# pre-install dependecies
- name: Load kernel modules
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Kernel modules config file
  ansible.builtin.copy:
    src: pre-install/modules.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Sysctl config file
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/k8s.conf
